import { ModuloPermiso } from './auth.model';

/** Nombre legible de cada módulo de permisos (matriz de roles, filtros de auditoría). */
export const ETIQUETAS_MODULO: Record<ModuloPermiso, string> = {
  NEGOCIOS: 'Negocios',
  NEGOCIO: 'Datos del negocio',
  SUCURSALES: 'Sucursales',
  USUARIOS: 'Usuarios',
  ROLES: 'Roles',
  PRODUCTOS: 'Productos',
  CATEGORIAS: 'Categorías',
  MARCAS: 'Marcas',
  LINEAS: 'Líneas',
  PROVEEDORES: 'Proveedores',
  BODEGAS: 'Bodegas',
  INVENTARIO: 'Inventario',
  VENTAS: 'Ventas',
  CAJA: 'Caja',
  COBROS: 'Cobros',
  CLIENTES: 'Clientes',
  DOMICILIOS: 'Domicilios',
  ALERTAS: 'Alertas',
  REPORTES: 'Reportes',
  METODOS_PAGO: 'Métodos de pago',
  GRAFICOS: 'Gráficos',
  FACTURACION: 'Facturación',
  CUPONES: 'Cupones y descuentos',
  PAGOS: 'Pagos con Wompi',
  TIENDA_ONLINE: 'Tienda online',
  PAQUETES: 'Paquetes',
  FACTURACION_ELECTRONICA_DIAN: 'Facturación electrónica DIAN',
  DEVOLUCIONES: 'Devoluciones',
  TRASLADOS: 'Traslados',
  AUDITORIA: 'Auditoría',
};
